defaults:
  - _self_
  - camera
  - network
  - robot: xarm_stick
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

storage_path: extracted_data/open_oven/
demo_num: 271
sim_env: false
is_xela: false
host: ${host_address}



hydra:  
  output_subdir: null  
  run:  
    dir: .