defaults:
  - _self_
  - network
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled 

# Start fisheye cam indices from 51
fisheye_cam_numbers:
  - 51: 12 # top
  - 52: 26 #fisheye
  
cam_configs:
  width: 640
  height: 480
  fps: 30
  

oculus_cam: 0 # First camera
stream_oculus: False

hydra:  
  output_subdir: null  
  run:  
    dir: .