defaults:
  - _self_
  - network
  - robot: xarm_stick
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  

# To run the robot 
operate: true
sim_env: false
run_xela:  false

# Visualize 3D and 2D plots
visualize_xela: false
visualize_right_2d:  false
visualize_right_3d: false
visualize_right_dir: false

hydra:  
  output_subdir: null  
  run:  
    dir: .